- hosts: dorcas_io_azure
  remote_user: ubuntu
  vars:
    git_branch: Tomide-branch
    dest_path: /var/www/api.dorcas.ng
    repo: https://ayotomideaina:G613hg3cXCxzni4stepW@gitlab.com/dorcasng/dorcas-base.git
    server_state: started
    etc:
      env:
        - settings:
            - name: "APP_NAME"
              value: "Dorcas"
            - name: "APP_ENV"
              value: "production"
            - name: "APP_KEY"
              value: "base64:qY8iqi+rdNRCoIwJMHOSIJttWywy5F2TRQDj8H2ju9g="
            - name: "APP_DEBUG"
              value: "false"
            - name: "APP_LOG_LEVEL"
              value: "debug"
            - name: "APP_URL"
              value: "https://api.dorcas.ng"
            - name: "APP_SITE_URL"
              value: "https://hub.dorcas.io"
            - name: "APP_URL_STATIC"
              value: "https://hub.dorcas.ng"
            - name: "SCOUT_PREFIX"
              value: "dorcas_prod_"
            - name: "AWS_ACCOUNT_ID"
              value: "161475284744"
            - name: "AWS_KEY"
              value: "AKIASLGFNJ4EKCBZLFLC"
            - name: "AWS_SECRET"
              value: "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"
            - name: "AWS_REGION"
              value: "eu-west-2"
            - name: "AWS_SES_REGION"
              value: "eu-west-1"
            - name: "AWS_BUCKET"
              value: "dorcas-s3"
            - name: "AWS_SQS_QUEUE"
              value: "dorcas-queue"
            - name: "AWS_KEY_EKO"
              value: "AKIAS75A2ZYDMUMM3PEV"
            - name: "AWS_SECRET_EKO"
              value: "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"
            - name: "AWS_SES_REGION_EKO"
              value: "eu-west-1"
            - name: "BUGSNAG_API_KEY"
              value: "519026f346382a05c93c85cb5e0f50d1"
            - name: "DB_CONNECTION"
              value: "mysql"
            - name: "DB_HOST"
              value: "dorcas-api.mysql.database.azure.com"
            - name: "DB_DATABASE"
              value: "dorcas"
            - name: "DB_DATABASE_STAGING"
              value: "dorcas_staging"
            - name: "DB_USERNAME"
              value: "dorcas@dorcas-api"
            - name: "DB_PASSWORD"
              value: "Jks7h-sJn3HA00AJ3n-JSnA@5"
            - name: "MAIL_FROM_ADDRESS"
              value: "hello@dorcas.ng"
            - name: "PAYSTACK_PUBLIC_KEY"
              value: "pk_live_701d138b55cd09c0eb9f0f2bf77d716d050c87b3"
            - name: "PAYSTACK_SECRET_KEY"
              value: "sk_live_67a75cbf57d27d8aa923b6509c7d7d58527669ba"
            - name: "ALGOLIA_APP_ID"
              value: "7GYZ8KL9NM"
            - name: "ALGOLIA_SECRET"
              value: "2af818cb20aa0356feef077259db0c0a"
            - name: "AZURE_QUEUE_NAME"
              value: "dorcas-hub-queue"
            - name: "AZURE_STORAGE_ACCOUNT"
              value: "dorcas"
            - name: "AZURE_STORAGE_NAME"
              value: "dorcas"
            - name: "AZURE_STORAGE_KEY"
              value: "sKBVAfm31PQ8taXhzqmvF9B63uB9D+w24LdwQ1dBhOQeE2ZxXbvXggdSyVgc0RN9052dUAF56qEi+L4Pn5Zizg=="
            - name: "AZURE_STORAGE_CONTAINER"
              value: "dorcas-storage"
            - name: "AZURE_STORAGE_URL"
              value: ""
            - name: "FILESYSTEM_DRIVER"
              value: "s3"
            - name: "REDIS_HOST"
              value: "dorcas-cache.redis.cache.windows.net"
            - name: "REDIS_PASSWORD"
              value: "GeTN1V6htgiT6KQBmplMp4wpuR5ukL9A0CP0Uoej87k="
            - name: "CACHE_DRIVER"
              value: "file"
            - name: "QUEUE_DRIVER"
              value: "redis"
            - name: "MAIL_DRIVER"
              value: "mailgun"
            - name: "MAILGUN_DOMAIN"
              value: "mg.dorcas.io"
            - name: "MAILGUN_SECRET"
              value: "a8e08585449bcf3bc04c8449d324270f-7238b007-3ef23eeb"
            - name: "BUGSNAG_API_KEY"
              value: "519026f346382a05c93c85cb5e0f50d1"
    supervisor:
      worker01:
        name: dorcas-worker
        settings:
          - name: "process_name"
            value: "%(program_name)s_%(process_num)02d"
          - name: "command"
            value: "php /var/www/api.dorcas.ng/artisan queue:work redis --sleep=3 --tries=3"
          - name: "autostart"
            value: "true"
          - name: "autorestart"
            value: "true"
          - name: "user"
            value: "www-data"
          - name: "numprocs"
            value: "4"
          - name: "redirect_stderr"
            value: "true"
          - name: "stdout_logfile"
            value: "/var/www/api.dorcas.ng/storage/logs/dorcas-worker.log"
  tasks:
    - name: stop supervisor
      command: supervisorctl stop all
      tags:
        - process_management
      become: yes
      become_method: sudo
    - name: clear out deploy path
      command: rm -rf {{ dest_path }}
      become: yes
      become_method: sudo
      tags:
        - cleanup
        - deploy
    - name: pull source from the gitlab repository
      git: repo={{ repo }} dest={{ dest_path }} accept_hostkey=yes version={{ git_branch | default('master') }}
      become: yes
      become_method: sudo
      tags:
        - pull
        - deploy
    - name: adjust privileges and ownerships for the directories
      file:
        path="{{ item.path }}"
        state={{ item.state | default(omit) }}
        mode={{ item.mode | default('u=rwx,g=rwx,o=rx') }}
        group={{ item.group | default('www-data') }}
        owner={{ ansible_user }}
        recurse={{ item.recurse | default(omit) }}
      with_items:
        - { path: "{{ dest_path }}", state: "directory", recurse: "yes" }
        - { path: "{{ dest_path }}/storage", state: "directory", recurse: "yes", mode: 'u=rwx,g=rwx,o=rwx' }
        - { path: "{{ dest_path }}/artisan", state: "file", mode: 'u=rwx,g=rx,o=x' }
      become: yes
      become_method: sudo
      tags:
        - configuration
        - permissions
    - include_tasks: ansible-automation/tasks/create-env-configuration.yml
      vars:
        filename: .env
        destination: "{{ dest_path }}/.env"
        config_section: "{{ etc.env }}"
      tags:
        - configuration
    - name: set permissions on all files
      command: find "{{ dest_path }}" -type f -name '*.php' -exec chmod 644 {} \;
      tags:
        - configuration
      become: yes
      become_method: sudo
    - name: get composer setup
      get_url: url=https://getcomposer.org/installer dest="{{ dest_path }}/composer-setup.php"
      tags:
        - composer
        - install
      become: yes
      become_method: sudo
    - name: install composer
      command: php composer-setup.php
      args:
        creates: composer.phar
        chdir: "{{ dest_path }}"
      tags:
        - composer
        - install
      become: yes
      become_method: sudo
    - name: remove composer-setup.php script
      file: path="{{ dest_path }}/composer-setup.php" state=absent
      tags:
        - composer
        - install
      become: yes
      become_method: sudo
    - name: install composer packages
      command: php composer.phar install
      args:
        chdir: "{{ dest_path }}"
      tags:
        - composer
        - install
      notify:
        - manage nginx
      become: yes
      become_method: sudo
    - include_tasks: ansible-automation/tasks/create-supervisor-program.yml
      vars:
        program: "{{ supervisor.worker01 }}"
        force: yes
      tags:
        - configuration
        - supervisord
    - name: reload supervisor daemon configuration files
      command: supervisorctl reread
      tags:
        - configuration
      become: yes
      become_method: sudo
    - name: update supervisor programs
      command: supervisorctl update
      tags:
        - configuration
      become: yes
      become_method: sudo
      notify:
        - start supervisor
    - name: install wkhtmltopdf dependencies - zlib, fontconfig, freetype, X11 libs (libX11, libXext, libXrender)
      apt: name={{ item.1 }} state=present update_cache=yes cache_valid_time=1200
      with_indexed_items:
        - openssl
        - build-essential
        - libssl-dev
        - libx11-dev
        - libxrender-dev
        - libxext-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - fontconfig
      become: yes
      become_method: sudo
  handlers:
    - name: manage nginx
      service: name=nginx state={{ server_state | default(started) }}
      become: yes
      become_method: sudo
    - name: start supervisor
      command: supervisorctl start all
      become: yes
      become_method: sudo
